name = "axis-reading-plan"
main = "./src/index"
route = "reading.sethaalexander.com/*"
account_id = "1ae24f064d5a7bfb3070959cf0181225"
workers_dev = true
compatibility_date = "2022-01-11"
kv_namespaces = [
	 { binding = "READING_PLAN_KV", id = "1621a031d1a542b990cfe6113c956ced", preview_id = "1621a031d1a542b990cfe6113c956ced" }
]
send_metrics = false